/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./resources/js/Components/ActionMessage.vue')['default']
    ActionSection: typeof import('./resources/js/Components/ActionSection.vue')['default']
    AuthenticationCard: typeof import('./resources/js/Components/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./resources/js/Components/AuthenticationCardLogo.vue')['default']
    Banner: typeof import('./resources/js/Components/Banner.vue')['default']
    ButtonLink: typeof import('./resources/js/Components/ButtonLink.vue')['default']
    CardBasic: typeof import('./resources/js/Components/CardBasic.vue')['default']
    CardIcon: typeof import('./resources/js/Components/CardIcon.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./resources/js/Components/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./resources/js/Components/ConfirmsPassword.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    DialogModal: typeof import('./resources/js/Components/DialogModal.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    FlashMessage: typeof import('./resources/js/Components/FlashMessage.vue')['default']
    FormSection: typeof import('./resources/js/Components/FormSection.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Layout: typeof import('./resources/js/Components/DataTable/Layout.vue')['default']
    LogoLetter: typeof import('./resources/js/Components/LogoLetter.vue')['default']
    LogoSign: typeof import('./resources/js/Components/LogoSign.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    Package: typeof import('./resources/js/Components/Package.vue')['default']
    Pagination: typeof import('./resources/js/Components/Pagination.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    Radio: typeof import('./resources/js/Components/Radio.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    Search: typeof import('./resources/js/Components/DataTable/Search.vue')['default']
    SearchFilter: typeof import('./resources/js/Components/SearchFilter.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    Section: typeof import('./resources/js/Components/Section.vue')['default']
    SectionBorder: typeof import('./resources/js/Components/SectionBorder.vue')['default']
    SectionTitle: typeof import('./resources/js/Components/SectionTitle.vue')['default']
    SelectInput: typeof import('./resources/js/Components/SelectInput.vue')['default']
    SingleView: typeof import('./resources/js/Components/DataTable/SingleView.vue')['default']
    SingleViewRow: typeof import('./resources/js/Components/DataTable/SingleViewRow.vue')['default']
    Subscription: typeof import('./resources/js/Components/Subscription.vue')['default']
    Switcher: typeof import('./resources/js/Components/Switcher.vue')['default']
    Tab: typeof import('./resources/js/Components/Tab.vue')['default']
    TableData: typeof import('./resources/js/Components/DataTable/TableData.vue')['default']
    TableHead: typeof import('./resources/js/Components/DataTable/TableHead.vue')['default']
    Tabs: typeof import('./resources/js/Components/Tabs.vue')['default']
    TextArea: typeof import('./resources/js/Components/TextArea.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
    Welcome: typeof import('./resources/js/Components/Welcome.vue')['default']
  }
}
